version: '3'
services:
  dbt:
    image: fishtownanalytics/dbt:latest
    container_name: dbt
    volumes:
      - ./dbt:/dbt
    command: ["dbt", "run"]
  
  airflow:
    image: apache/airflow:latest
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_LOAD_EXAMPLES=no
    volumes:
      - ./superset:/home/superset
    command: ["superset", "run", "-p", "8088", "--with-threads", "--reload"]

  portal:
    image: nginx:latest
    container_name: portal
    ports:
      - "80:80"
    volumes:
      - ./portal:/usr/share/nginx/html:ro
